#!/bin/bash
#Fix for pt-input 1.0.0 for Raspbian Stretch

dpkg -s "libicu52" &> /dev/null

if [ $? -eq 0 ]
then
  echo "libicu52 is already installed. Nothing to fix."
else
  if grep -q "stretch" /etc/apt/sources.list
  then
    echo "Executing in Raspbian Stretch: installing libicu52 from jessie repo"
    echo "Do not interrupt installation!"
    sudo sed -i "s/stretch/jessie/g" /etc/apt/sources.list
    sudo apt update
    sudo apt install -y libicu52
    sudo sed -i "s/jessie/stretch/g" /etc/apt/sources.list
    sudo apt update
    echo "Done!"
  else
    echo "This fix is only for Raspbian Stretch!"
  fi
fi