#!/bin/bash
# install pi-top-Configuration and tools

sudo cp pt-setup /usr/bin
sudo chmod +x /usr/bin/pt-setup
sudo cp pt_config.desktop /usr/share/applications
echo "menu->Preferences->pi-top Configuration is now available"

echo "Installing additional tools:"

# create bin directory in ~, if it does not exist
[ ! -d ~/bin  ] && mkdir ~/bin

cp tools/pt-log ~/bin
chmod +x ~/bin/pt-log
echo "pt-log has been installed"

cp tools/pt-devices ~/bin
chmod +x ~/bin/pt-devices
echo "pt-devices has been installed"

cp tools/audiotest ~/bin
chmod +x ~/bin/audiotest
echo "audiotest has been installed"

cp tools/touchpad ~/bin
chmod +x ~/bin/touchpad
echo "touchpad has been installed"

