#!/bin/bash
# pt-log:Show log of pt-device-manager (current boot), exclude unneccessary lines

journalctl -u pt-device-manager --since=yesterday | grep -v GET_BATTERY_STATE | sed 's/pitop \/usr\/lib\/pt-device-manager\///g'
